############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "About Us"
url = "team/"
weight = 2

[[main]]
name = "Why Vision Pro"
url = "vision-pro/"
weight = 3

[[main]]
name = "Career"
url = "https://wellfound.com/company/juliette-inc/jobs"
weight = 4

# [[main]]
# weight = 4
# name = "Pages"
# hasChildren = true

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "blog/"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "authors/"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
[[footer]]
name = "About"
url = "team/"
weight = 1

[[footer]]
name = "Career"
url = "https://wellfound.com/company/juliette-inc/jobs"
weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
